# Generated by Django 4.2 on 2023-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companyprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companynames', models.CharField(max_length=250)),
                ('fields', models.CharField(choices=[('IT Field', 'IT Field'), ('e-Commerce', 'e-Commerce'), ('electrical', 'Elecrical'), ('Auto-mobile', 'Auto-mobile'), ('Engeneering', 'Engeneering')], default='IT Field', max_length=200)),
                ('descriptions', models.TextField(max_length=200)),
                ('phones', models.CharField(max_length=200)),
                ('emails', models.EmailField(blank=True, max_length=254, null=True)),
                ('establishes', models.CharField(max_length=200)),
                ('quotes', models.TextField(max_length=200)),
                ('websites', models.CharField(max_length=300, unique=True)),
                ('gits', models.CharField(max_length=300, unique=True)),
                ('youtubes', models.CharField(max_length=300, unique=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='company_image/')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.PositiveBigIntegerField()),
                ('work', models.CharField(max_length=200)),
                ('workpic', models.ImageField(blank=True, null=True, upload_to='work_image/')),
                ('workdisc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('jobname', models.CharField(max_length=200)),
                ('qualification', models.CharField(choices=[('+2', '+2'), ('Degree', 'Degree'), ('btech', 'Btech')], default='+2', max_length=100)),
                ('experiances', models.CharField(choices=[('fresher', 'fresher'), ('1 year above', '1 year above'), ('2-3year above', '2-3year above'), ('4-5 year above ', '4-5 year above ')], default='fresher', max_length=100)),
                ('description', models.TextField()),
                ('shortdes', models.TextField()),
                ('requiredskill', models.CharField(max_length=200)),
                ('vaccancy', models.IntegerField(verbose_name=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
