# Generated by Django 4.2 on 2023-05-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('comapny', '0002_companyprofile_ref_comodel_jobpost_ref_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='ref_admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_view'),
            preserve_default=False,
        ),
    ]
