# Generated by Django 4.2 on 2023-07-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('comapny', '0003_companyprofile_ref_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='fields',
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(choices=[('IT Field', 'IT Field'), ('e-Commerce', 'e-Commerce'), ('electrical', 'Elecrical'), ('Auto-mobile', 'Auto-mobile'), ('Engeneering', 'Engeneering')], default='IT Field', max_length=200)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
