# Generated by Django 4.2 on 2023-07-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0004_remove_companyprofile_fields_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='ref_comodel',
        ),
    ]
