# Generated by Django 4.2 on 2023-07-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0007_remove_companyprofile_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='Post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
