# Generated by Django 4.2 on 2023-07-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0010_alter_recentwork_ref_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='ref_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile'),
        ),
    ]
