# Generated by Django 4.2 on 2023-07-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('comapny', '0012_alter_recentwork_ref_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='ref_profle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
            preserve_default=False,
        ),
    ]
