# Generated by Django 4.2 on 2023-08-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('comapny', '0013_companyprofile_ref_profle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='experiances',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='jobname',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='ref_company',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='refmodel',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='requiredskill',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='shortdes',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='vaccancy',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='education_rqmnts',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_field',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='ref_company_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='vacancies',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
