# Generated by Django 4.2 on 2023-08-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0014_remove_jobpost_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
