# Generated by Django 4.2 on 2023-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0015_jobpost_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_image/'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='vacancies',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
