# Generated by Django 4.2 on 2023-08-05 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0017_remove_jobpost_ref_company_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='ref_profile2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile'),
        ),
    ]
