# Generated by Django 4.2 on 2023-08-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('comapny', '0018_recentwork_ref_profile2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='ref_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='ref_profile2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile'),
            preserve_default=False,
        ),
    ]
