# Generated by Django 4.2 on 2023-08-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0019_alter_recentwork_ref_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ref_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comapny.companyprofile'),
            preserve_default=False,
        ),
    ]
