# Generated by Django 4.2 on 2023-08-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0020_jobpost_ref_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='ref_profile',
        ),
    ]
