# Generated by Django 4.2 on 2023-09-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0024_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comapny.jobpost'),
            preserve_default=False,
        ),
    ]
