# Generated by Django 4.2 on 2023-09-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0025_replay_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replay',
            name='company',
        ),
    ]
