# Generated by Django 4.2 on 2023-09-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0026_remove_replay_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
