# Generated by Django 4.2 on 2023-04-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Companyprofile',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
