# Generated by Django 4.2 on 2023-04-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
