# Generated by Django 4.2 on 2023-05-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('jo', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ref_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user2'),
            preserve_default=False,
        ),
    ]
