# Generated by Django 4.2 on 2023-08-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('jo', '0005_userprofile_ref_comfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ref_comfile',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ref_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2'),
        ),
        migrations.CreateModel(
            name='Marital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital', models.IntegerField(default=False)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_choice', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='IT Field', max_length=200)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
            ],
        ),
    ]
