# Generated by Django 4.2 on 2023-08-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0006_remove_userprofile_ref_comfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marital',
            old_name='gender',
            new_name='marital_user',
        ),
    ]
