# Generated by Django 4.2 on 2023-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0007_rename_gender_marital_marital_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='marital',
            name='marital',
            field=models.BooleanField(default=False),
        ),
    ]
