# Generated by Django 4.2 on 2023-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0008_remove_userprofile_linkedin_alter_marital_marital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='marital',
            name='marital_user',
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender_choice',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=200),
        ),
    ]
