# Generated by Django 4.2 on 2023-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0011_remove_gender_user_remove_marital_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marital',
            name='marital',
            field=models.CharField(max_length=50),
        ),
    ]
