# Generated by Django 4.2 on 2023-08-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0012_alter_marital_marital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ref_martial',
        ),
        migrations.DeleteModel(
            name='Marital',
        ),
    ]
