# Generated by Django 4.2 on 2023-08-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comapny', '0018_recentwork_ref_profile2'),
        ('account', '0003_delete_user_user2'),
        ('jo', '0013_remove_userprofile_ref_martial_delete_marital'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume', models.FileField(null=True, upload_to='files/')),
                ('education', models.TextField()),
                ('experiance', models.TextField()),
                ('is_confirm', models.BooleanField()),
                ('ref_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comapny.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
            ],
        ),
    ]
