# Generated by Django 4.2 on 2023-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0014_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='skill',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
