# Generated by Django 4.2 on 2023-08-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0015_jobapplication_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ref_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jo.jobapplication'),
            preserve_default=False,
        ),
    ]
