# Generated by Django 4.2 on 2023-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0018_remove_userprofile_ref_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
