# Generated by Django 4.2 on 2023-08-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('jo', '0019_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workexperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('discription', models.TextField()),
                ('position', models.CharField(max_length=250)),
                ('stating_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
                ('college', models.CharField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
            ],
        ),
    ]
