# Generated by Django 4.2 on 2023-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0020_workexperiance_projects_educations'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
