# Generated by Django 4.2 on 2023-08-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0021_projects_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='project',
        ),
    ]
