# Generated by Django 4.2 on 2023-08-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('jo', '0022_rename_title_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=260)),
                ('vertion', models.CharField(max_length=50)),
                ('last_used', models.DateField()),
                ('experiance', models.IntegerField()),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('certificate_name', models.CharField(max_length=250)),
                ('ref_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile')),
            ],
        ),
    ]
