# Generated by Django 4.2 on 2023-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0023_itskills_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itskills',
            name='experiance',
            field=models.FloatField(),
        ),
    ]
