# Generated by Django 4.2 on 2023-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0024_alter_itskills_experiance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itskills',
            name='experiance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itskills',
            name='vertion',
            field=models.FloatField(),
        ),
    ]
