# Generated by Django 4.2 on 2023-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0025_alter_itskills_experiance_alter_itskills_vertion'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certificate',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
