# Generated by Django 4.2 on 2023-09-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_user2'),
        ('jo', '0030_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ref_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user2'),
            preserve_default=False,
        ),
    ]
