# Generated by Django 4.2 on 2023-09-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0034_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jo.userprofile'),
            preserve_default=False,
        ),
    ]
