# Generated by Django 4.2 on 2023-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo', '0035_replay_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
